### ISSUE TITLE
Backup sysnand make my sd ureadeable

### ISSUE THREAD

**Issue by Stiggia** [d0k3/Decrypt9WIP#103]
It look wiered to me but i tryed two times and both of the time after backup my sd can be read nether from pc non 3ds.

is my sd broken or is some kind of bug?

**Comment by d0k3** [comment]
That's a problem with your SD card, obviously. Did you get any error message in D9?

**Comment by Stiggia** [comment]
the firt time backup failed and the second succeded

No message.

**Comment by d0k3** [comment]
This is a problem with your SD card and/or file system. Maybe just a specific area is affected, or the actual capacity is lower than the advertised one (would help to know which brand this card is and where you bought it). The reason why that problem is only triggered with NAND backups is that a NAND backup is a big (1GB+) file.

Try with a different SD card, also test the one your currnetly using via h2testw:
http://translate.google.com/translate?hl=en&sl=de&u=http://www.heise.de/software/download/h2testw/50539&prev=/search%3Fq%3Dheise%2Bh2testw%26hl%3Den%26sa%3DG

I'm lcosing this now, but feel free to reopen if h2testw does not turn up anything and / or a different SD card does not work either.

**Comment by Stiggia** [comment]
ty for the tip i'm gonna try.

there is a linux way?
