### ISSUE TITLE
E-Manual Doesn't Works via CIA DUMP Function

### ISSUE THREAD

**Issue by sifiro** [d0k3/Decrypt9WIP#116]
Hi, I Have a 2DS European with A9LH (Luma3DS Last Version etc).
I Dumped Senran Kagura 2: Deep Crimson (USA) Via Decrypt9 CIA Dump And the Games Works.
But doesn't Work e-manual.
I dumped CIA twice, once with a old Version of Decrypt9 (I Dumped .3ds and cia) and last version (2016-11-13) (only Cia), so Both Doesn't Works.
And with 3ds dump and 3DS Simple CIA Converter it's Works (and too with Retail Cartridge)
I Think that is a bug... (?)

I Record a Video with the problem:
https://www.youtube.com/watch?v=ZofwiSvyNOs
Thanks and... I Apologize with my writing, English isn't my native language.

**Comment by d0k3** [comment]
Okay, I guess I will need more info from you. Problem here is, I don't have that cart. Could you try converting the working .3DS file via D9? You'll need to use the NCCH/NCSD CIA Builder in Content Decryptor -> CIA Builder

**Comment by d0k3** [comment]
Additionally, one more thing that you could help me with, is using a hex editor to find the first difference between the working CIA and the non working one. HxD, for example, can do it. Post a screenshot if you can.

**Comment by sifiro** [comment]
Yeah, i Can, No Problemo  ;D
http://imgur.com/a/OwqDJ
Now if you want, i Can upload both CIAS.

**Comment by d0k3** [comment]
Just a quick heads up. Thanks for the data you provided, but I'm still clueless. If the CIA installs, everything should be fine, and the manual content is exactly the same in the 'working' and 'non working' ones (the TMD contains the hash, just in case you wonder).

I'll need to think about this some more, in the meantime - can you make absolutely, 100% sure nothing went wrong on your side.

**Comment by sifiro** [comment]
I'm Gonna do another "NCCH/NCSD CIA Builder" .cia, with a EmuNand Clean.
Only for Checks Purpose.
and one thing, check the log included with the zip
there is a "Warning, could not read secure key." , "Error, exheader hash mismatch, Wrong Key?". with ".3ds".
and maybe it's me but...
 logs from cias
Hash is different TMD content0
working:
"36B1CFB76A82BB05355631E882E76CF9FD29C249F22DEE649EECAAC786D5D90C"
requested:
"BE5C6B4843D066145BE0D467BC46361EBE8A8E48D238AB3B62475AB8989E9721"

content1 is the same.
and yeah, content 0 is 2,1GB Partition and Content 1 a few MB (i'dont remember now)

and...
Header request is full FF (15) (and this is weird)
worked version has a header reasonable (my opinion, I don't know, I am not in Scene)

**Comment by sifiro** [comment]
Summary:
Emunand Clean.
Create a new CIA with "NCCH/NCSD CIA Builder" Again Install SK2:DC USA in Emunand - Doesn't Work e-Manual
Dump CIA Function Shovel Knight EUR and install in Emunand = E-Manual Works
DUMP ".3ds" again with newest D9: Same Checksum that first dump .3ds. Soo ".3ds" is Well Dumped.

Next Test I Will testing with Bravely Default (if was a Big CIA size Issue) and... I Don't Have another USA Cart for testing... xd

**Comment by d0k3** [comment]
Alright, I see you're not a noob ;).

The hash for content 0 is different, but that is okay. Content 0 is the CXI, the playable content. Maybe the D9 created playable content is a little different than the other one, but that is okay. As you see, it is playable.

Content 1 is the e-manual. As you see, it is identical.

The stuff in the log should be fine. Not one hundred percent sure, though.

The all 0xFF signature is nothing to care about. CFW have sig patching enabled, you can actually write anything there.

If something in the CIA structure itself would be wrong, it wouldn't be installable via FBI. No chance actually, cause normally even a 1 byte difference will lead to a fully corrupted CIA.

The size difference between the D9 generated CIA and the otehr one is due to the D9 CIA having metadata, and the other not (check it in FBI, only for the D9 generated one the icon and name shows up).

So... what now? I'm a bit clueless, but I think, yes, this may have to do with region. I'll need to ask around, maybe I can come up with something tomorrow,

**Comment by sifiro** [comment]
I don't know how works Luma3DS, but by default should patch from HomeMenu all Cias and Cart.
Right? (Up, Video load my USA Cart, and load e-manual, it's so Strange), and yeah, Could be that 3ds simple cia converter Cias works e-manual bacause Region Free Patches.

**Comment by sifiro** [comment]
All Right, is a Luma3DS Issue.
If are there some method for move a repository to another.
please move, if not... I Close this Issue and open another Issue in Luma3DS

**Comment by sifiro** [comment]
There are a reported Issue so...
https://github.com/AuroraWright/Luma3DS/issues/150
close this issue.
I Repeat, I'am Pretty sorry.

**Comment by d0k3** [comment]
Oh, alright. Thanks for pointing this out!
