### ISSUE TITLE
AK2i Bootrom Restore doesnt work properly.

### ISSUE THREAD

**Issue by CaelThunderwing** [d0k3/Decrypt9WIP#137]
Mine had a CHIP ID of 0X0FC2 HW ID: 81 after restore it now shows HW8181 in Decrypt9 & FW Updater for DSi 1.4.4 & 3DS 4.3

my Dump was made while on said FW Update, after restore Icon shows AK2 Logo (no AK2i or the "Pippa Funnel" Icon), i had to use Apache Thunder's NTRLauncher to boot the card and re-run the 1.4.4 Updater to restore functionality.

**Comment by d3m3vilurr** [comment]
can you provide your ak2i_patch.bin to my email?
d3m3vilurr at gmail.com

**Comment by d0k3** [comment]
@d3m3vilurr is the author of this functionality. I'll try to help, but I'm of limited use in this.

**Comment by d3m3vilurr** [comment]
ok. this issue is ignorable. I was contacted issued person who named `Dracari` on the gbatemp.
(I don't know same person, anyway)

1. many issues are looks related flashing with NTRLauncher on 3DS.
2. HW8181 exactly same HW81; AK2i always returne 4242 or 8181, but just code [masked 0xFF](https://github.com/d0k3/Decrypt9WIP/blob/8a035fb/source/gamecart/command_ak2i.c#L20).
3. maybe we need regenerate `ak2i_flash.bin` before restore. [current code](https://github.com/d0k3/Decrypt9WIP/blob/855c63d/source/decryptor/ak2i.c#L778-L780) can allow broken file.

**Comment by d0k3** [comment]
So... should we close it? Any fixes required?

**Comment by d3m3vilurr** [comment]
yep can close this. we can fix `3` at next time (imo, it's optional)

**Comment by d0k3** [comment]
If it's a simple fix... better to prevent this instead of having issues pop open. Anyways, closing this now, and if you can / want to fix this, just send a pull request.
