### ISSUE TITLE
Having a problem to use the code

### ISSUE THREAD

**Issue by maxjanebruno** [d0k3/Decrypt9WIP#161]
My 2ds left buttom is not working. I use the buttons from the analog pad. So i have a problem with decrypt9 since i can't press LEFT. Is there any chance i can use it without having to press it? Please, help me.

**Comment by d0k3** [comment]
You can change what these buttons are defined to here:
https://github.com/d0k3/Decrypt9WIP/blob/master/source/hid.h

F.e.: #define BUTTON_LEFT   (1 << 11) makes the Y button act as left button.

If you can't compile, get someone to help you, and if you don't understand how to change the file, I'm sure someone else can help, too.

Closing this now, because it is not a Github issue.

**Comment by maxjanebruno** [comment]
Hi,
Thanks for your response.
I already changed the file, but how can i compile it? Can u help me? With
software should i use?

Thanks.

2017-03-01 6:22 GMT-03:00 d0k3 <notifications@github.com>:

**Comment by maxjanebruno** [comment]
Hi, never mind.
I did it!
:-) so happy! Big thanks to you!

2017-03-01 21:04 GMT-03:00 Bruno Gabriel <brunogabriel.rj@gmail.com>:
