### ISSUE TITLE
[IDEA] Autoupload xorpads for consoles

### ISSUE THREAD

**Issue by PokeAcer549** [d0k3/Decrypt9WIP#57]
I've had a small idea;
Add an option to generate xorpads that could save a 3DS from being bricked, and then upload them to a server, which could then store them under a certain serial, aswell as a NAND backup, so if anything is to occur to the users' computer they could get a copy back.

They'd be kept in a manner which nobody could touch them (plus nobody would be able to use them anyways except for the orig. console)

**Comment by d0k3** [comment]
ARM9 software does not have access to the internet, also that server would have to be provided. XORpads can't be compressed, too, so that would be a rather large upload for everyone.

Plus, you don't actually need that XORpad to save yourself from a brick, you can regenerate it with a9lh. To install a9lh to any NAND image, see here:
https://github.com/al3x10m/A9LH-Injector

If you want to continue on with this project, one more hint.... the real important files are NAND header, SecureInfo_A, movable.sed, title.db, ticket.db, otp.bin.

**Comment by PokeAcer549** [comment]
Someone could in theory make something on the 3DS itself (ie in sys/emu NAND) that uploads it. Plus, I can provide servers.

**Comment by urherenow** [comment]
Maybe I'm OCD because if you tagged this issue as [Feature Request], I'd have no problem with it, but the [Idea] tag makes my blood boil and I want to remind you that github is NOT a forum.

Still, what good will an xorpad do for a bricked ststem? None. None at all. It doesn't do anything without a NAND backup, and said NAND backup is what you really need to unbrick a console.

Considering that all needed xorpads combined are exactly the same size as the NAND backup... What the hell are you thinking?

**Comment by d0k3** [comment]
What @urherenow just said. What you really want to go for is the NAND backup. This is actually slightly bigger than the XORpads uncompressed, but much smaller compressed. And, if you want a minimum solution, take the 6 files I mentioned, these are enough to get the console back into working state, although not easily.

And, as for that server... I wouldn't want to let my 3DS run 3...4h uploading this (bad internet speed here). Given that, such a server already exists. It is called DropBox for me, and only I have access to my NAND backups on there.

Closing this now, we can continue this discussion elsewhere if you want.

**Comment by urherenow** [comment]
@d0k3 you just *think* it's smaller because you're used to looking at the xorpad for ctrnand; it doesn't include firm0/1. Combined, it's exactly the same size. That's how xor works...

**Comment by d0k3** [comment]
Nope, cause there are unused areas in the NAND flash memory, @urherenow. The header is not encrypted, too. For sector0x96 there can't be XORpad (AES ECB), sectors0x1...0x95 are completely unused.

Also, you'd have to include TWLN / TWLP XORpads for it to be complete.

**Comment by urherenow** [comment]
I did say "combined". 00 xor still == 00. Decrypt9WIP does all partition xors AFAIK.

**Comment by urherenow** [comment]
Anyway, don't mean to split hairs. I'm just a bit drunk. I'll stop now. I'm breaking my own resolve here (treating github like a forum).
