### ISSUE TITLE
[SUGGESTION] Add to Decrypt9 the Abiltiy to Dump Games and...

### ISSUE THREAD

**Issue by x7l7j8cc** [d0k3/Decrypt9WIP#60]
Hi, please, if you can, can you add the ability to Dump the Game Cartridges and let Decrypt9 convert the dump .3ds directly to .cia ???
This can be more easy for who want to dump his own cart and install as cia.

Without the need to dump it with one tool to .3ds, then go to pc and create ncch, then transfer the ncch to 3ds, generate xorpads, then go back to pc and create cia.

This can be a cool idea, but only if this can be done. :)

**Comment by d0k3** [comment]
This has been asked and thought over before. The uncart dumper code is too complicated and also doesn't play well with D9 code, so that's that. 3DS -> CIA conversion is not trivial, and makerom is doing it's job fine. It is doing that job so good, actually, that I could never achieve the same quality in D9. So, in short, I'm not doing it.

I will, however, add the decryptor code to uncart, thus you will only need to (1) dump, then (2) direct convert to CIA. No D9 required.

**Comment by x7l7j8cc** [comment]
So, if i understand correctly, you will add the convert code to Uncart, to directly convert 3ds to cia?

**Comment by d0k3** [comment]
No, CIA conversion is still not trivial and will need makerom. No way around it. But you won't need to handle D9 or XORpads anymore.

**Comment by d0k3** [comment]
If you haven't noticed, cart dumping is in there now :).
