### ISSUE TITLE
Unable to install Decrypt9WIP converted .CIA in GW mode

### ISSUE THREAD

**Issue by MelonGx** [d0k3/Decrypt9WIP#95]
The error message:
![123](https://cloud.githubusercontent.com/assets/7697767/18959453/ccd341da-8698-11e6-9b54-6a8f5e806fad.jpg)

The installation failed in GW mode, but succeeded in Luma.
I tried to dump the Luma-installed one and converted it with SDto3DS, it displayed this:
![234](https://cloud.githubusercontent.com/assets/7697767/18959594/57062fca-8699-11e6-8524-9c28ec3e1f8d.png)

**Comment by ihaveamac** [comment]
I think Gateway doesn't support modified contents besides the first one (the game executable). all of the contents are decrypted, which breaks the signature of the manual/etc.

**Comment by MelonGx** [comment]
The installation also failed with 3DS Simple Converter converted .CIA.
Seems that the problem is not caused by the NCCH -> CIA step?

Here's what I had done before the NCCH -> CIA:
1) Content Decryptor Options -> SD File Options... -> SD Decryptor (SysNAND dir) -> /title/00040000/001a7600/ -> Press A to decrypt this title
2) Unmount SD -> Put the SD on PC -> Copy 00000000.tmd, 00000000.app, 00000001.app to SDto3DS's folder
3) Run SDto3DS.py to convert them into .3DS. (It succeeded smoothly)

**Comment by d0k3** [comment]
@ihaveamac has nailed it. The issue is in GW not properly patching sigs. Why? Cause they not only code shit software, they are also lazy cashgrabs. 

The only way around would be a separate menu entry for dumping of encrypted CIA instead of decrypted.

Do we want this, though, and will this lead to anything but confusion? While I'm still thinking about it, I'm inclined to say, dont install CIA in GW mode. It is simply not worth it.
