### ISSUE TITLE
Health & Safety injection problems on Gateway downgraded console

### ISSUE THREAD

**Issue by valent-ex** [d0k3/Decrypt9WIP#96]
I'm having problems injecting FBI to Health & Safety app.

Universal Inject Generator:

- Successfully generated FBI_inject app file via generator.
- Successfully injected it via Decrypt9WIP.
- But 3DS still launches default Health & Safety app...

_(successfully = without errors)_

Using fbi-2.4.2-injectable.zip from Plailect Guide:

- Decrypt9WIP does not see any app files from that archive...

I'm on 11.1 CFW (A9LH/Luma).

**Comment by fox8091** [comment]
Did you ever downgrade with the Gateway launcher?

**Comment by valent-ex** [comment]
@fox8091 yeah, I've used Plailect guide on 4.5.0 downgraded by Gateway.

**Comment by valent-ex** [comment]
I am assuming that this is the solution:
https://gbatemp.net/threads/testers-needed-injecting-apps-to-h-s-on-a-gw-downgraded-nand.404059/#post-5854644

**Comment by d0k3** [comment]
No. Stop.

**Comment by d0k3** [comment]
Alright. The GW downgrade is a dirty one, it leaves basically two versions of each app on your system, one of them not being used. I'll tell you what you need to do, try to figure out the rest yourself. I hope you're already a9lh'd, too, cause otherwise you will have to pay extra attention.

Use GodMode9 to take a look into your CTRNAND://title/00040010/????????/content folder.
"????????" in that case is, depending on O3DS/N3DS and region one of:
00020300, 00021300, 00022300, 00026300, 00027300, 00028300, 20020300, 20021300, 20022300, 20027300

Now, in that folder, you've got two sets of app and tmd files - one set with uppercase extensions (.TMD, .APP), one set with lowercase extensions (.tmd, .app). Try deleting the uppercase set first, retry the injection. If it does not work, go back and try with the lowercase set.

If you do this to the correct folder this is not dangerous at all. Just don't mix up the numbers.

**Comment by valent-ex** [comment]
@d0k3 deleted set with uppercase extensions and injection worked! Thanks, man!

I know thats not cool to clean shit after someone, but having a "gateway cleanup tool" or at least a tutorial about this problem would be really nice 😉

Renamed issue, hope this will help someone else.

**Comment by Starboltz** [comment]
Hi everyone, i have the same issue, i downgraded my 3ds with GW, but when i follow the troubleshooting, i have 2 files of .tmd(lowcase and upper) and only one .app(uppercase), when i use the pair of lowcase, not work, open health & safety, when a switch the .app, leaving the .tmd lowcase and de .app uppercase, says that is corrupted or something like that....any thoughts? thanks guys!
